/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package tarski;

public class tarski {
  public static void TARSKIINIT(int numcells, int timeout) {
    tarskiJNI.TARSKIINIT(numcells, timeout);
  }

  public static String TARSKIEVAL(String input) {
    return tarskiJNI.TARSKIEVAL(input);
  }

  public static void TARSKIEND() {
    tarskiJNI.TARSKIEND();
  }

}
