/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.geogebra.common.cas.tarski;

public class tarskiJNI {
  public final static native void TARSKIINIT(int jarg1, int jarg2);
  public final static native String TARSKIEVAL(String jarg1);
  public final static native void TARSKIEND();
}
